// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/track-dossier.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { z } from "npm:zod@^4.4.3";
var track_dossier_default = defineTool({
  name: "track_dossier",
  title: "Track a Yobbant\xE9 shipment",
  description: "Look up the current status and public timeline of a Yobbant\xE9 shipment by its tracking ID (e.g. 'GDBR62').",
  inputSchema: {
    tracking_id: z.string().trim().min(3).describe("Public tracking ID of the dossier / shipment.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tracking_id }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.rpc("lookup_dossier_public", {
      _tracking_id: tracking_id.toUpperCase()
    });
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No shipment found for tracking ID ${tracking_id}.` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { dossier: data }
    };
  }
});

// src/lib/mcp/tools/list-departures.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_departures_default = defineTool2({
  name: "list_upcoming_departures",
  title: "List upcoming Yobbant\xE9 departures",
  description: "List upcoming scheduled shipment departures on the Yobbant\xE9 network (route, date, capacity).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("Maximum number of departures to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const url = process.env.SUPABASE_URL;
    if (!url) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const res = await fetch(`${url}/functions/v1/list-departures`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ limit })
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Departures unavailable (${res.status}).` }],
        isError: true
      };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { departures: data }
    };
  }
});

// src/lib/mcp/tools/get-shipping-rate.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_shipping_rate_default = defineTool3({
  name: "get_shipping_rate",
  title: "Estimate a Yobbant\xE9 shipping rate",
  description: "Estimate shipping cost and ETA for a parcel to a given destination country/city, based on weight in kg.",
  inputSchema: {
    destination_country: z3.string().trim().min(2).describe("Destination country name or ISO code (e.g. 'France', 'FR')."),
    destination_city: z3.string().trim().optional().describe("Destination city (optional)."),
    weight_kg: z3.number().positive().describe("Parcel weight in kilograms.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ destination_country, destination_city, weight_kg }) => {
    const url = process.env.SUPABASE_URL;
    if (!url) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const res = await fetch(`${url}/functions/v1/get-shipping-rates`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ destination_country, destination_city, weight_kg })
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Rate estimate unavailable (${res.status}).` }],
        isError: true
      };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "yobbante-mcp",
  title: "Yobbant\xE9",
  version: "0.1.0",
  instructions: "Yobbant\xE9 is a logistics orchestration platform (shipping between Europe/Africa and worldwide). Use `track_dossier` to look up a shipment by its public tracking ID, `list_upcoming_departures` to see scheduled departures on the network, and `get_shipping_rate` to estimate cost and ETA for a parcel.",
  tools: [track_dossier_default, list_departures_default, get_shipping_rate_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
