
INSERT INTO public.custom_cities (city, country_code, country_label, flag, active) VALUES
('Abidjan','CI','Côte d''Ivoire','🇨🇮',true),
('Alméria','ES','Espagne','🇪🇸',true),
('Bamako','ML','Mali','🇲🇱',true),
('Barcelone','ES','Espagne','🇪🇸',true),
('Berlin','DE','Allemagne','🇩🇪',true),
('Beyrouth','LB','Liban','🇱🇧',true),
('Bordeaux','FR','France','🇫🇷',true),
('Brazzaville','CG','République du Congo','🇨🇬',true),
('Bruxelles','BE','Belgique','🇧🇪',true),
('Casablanca','MA','Maroc','🇲🇦',true),
('Conakry','GN','Guinée','🇬🇳',true),
('Douala','CM','Cameroun','🇨🇲',true),
('Dubaï','AE','Émirats Arabes Unis','🇦🇪',true),
('Düsseldorf','DE','Allemagne','🇩🇪',true),
('Gatineau','CA','Canada','🇨🇦',true),
('Genève','CH','Suisse','🇨🇭',true),
('Istanbul','TR','Turquie','🇹🇷',true),
('Kinshasa','CD','République Démocratique du Congo','🇨🇩',true),
('Libreville','GA','Gabon','🇬🇦',true),
('Lille','FR','France','🇫🇷',true),
('Lyon','FR','France','🇫🇷',true),
('Madrid','ES','Espagne','🇪🇸',true),
('Malabo','GQ','Guinée Équatoriale','🇬🇶',true),
('Marseille','FR','France','🇫🇷',true),
('Milan','IT','Italie','🇮🇹',true),
('Montpellier','FR','France','🇫🇷',true),
('Montréal','CA','Canada','🇨🇦',true),
('N''Djamena','TD','Tchad','🇹🇩',true),
('New York','US','États-Unis','🇺🇸',true),
('Nîmes','FR','France','🇫🇷',true),
('Ottawa','CA','Canada','🇨🇦',true),
('Paris','FR','France','🇫🇷',true),
('Providence','US','États-Unis','🇺🇸',true),
('Rennes','FR','France','🇫🇷',true),
('Rouen','FR','France','🇫🇷',true),
('Washington','US','États-Unis','🇺🇸',true),
('Yaoundé','CM','Cameroun','🇨🇲',true)
ON CONFLICT (country_code, city) DO UPDATE SET active = true;
